### ISSUE TITLE
Mutability of LAPIC

### ISSUE THREAD

**Issue by tsatke** [kwzhao/x2apic-rs#16]
I'm using the `LAPIC` in my kernel which supports preemptive multitasking. I have it behind a `Mutex` because I hold it in a `static`.

Every so often I run into deadlocks, because I guess two interrupts try to lock at the same time, and if one of those is the timer interrupt, no reschedule will happen. If I don't call it at the end of the interrupt timer, no reschedule will happen, because no more interrupts arrive.

I'm creating this issue because I'm not sure whether I'm using the LAPIC wrong, whether I'm missing some features or whether maybe I should be able to call `end_of_interrupt` without a mutable reference to the APIC?

**Comment by Freax13** [comment]
[This section](https://github.com/tsatke/devos/blob/ffc3b860e8dd69d02e8d4b9e1158b403b879bcdd/kernel/src/arch/x86_64/idt.rs#L234-L237) in your kernel seems a bit dubious to me:
1. Why are calling `end_of_interrupt` in the page fault handler? Page faults aren't delivered by the LAPIC, so usually no eoi is necessary.
2. Enabling interrupts *before* calling `end_of_interrupt` allows the following race condition: 1. A page fault occurs. 2. Interrupts are enabled. 3. `end_of_interrupt` acquires the spin lock. 4. A timer interrupt (other any other interrupt) interrupts `end_of_interrupt`, before `end_of_interrupt` can release the spin lock it had acquired. 5. The timer interrupt handler executes `end_of_interrupt`. 6. `end_of_interrupt` stalls because the spin lock has already been acquired in step 4 and has not been released.

**Comment by tsatke** [comment]
Yeah that makes sense, and it fixes the issue for me (now), thanks!. But the LAPIC can deliver more interrupts, and can even deliver multiple interrupts even before one of the former has been ended with an EOI, right? So if I were to use IPIs and timer interrupts for example, I would have the same problem again, no?
Is that just something that is normally not done?

**Comment by Freax13** [comment]
> But the LAPIC can deliver more interrupts, and can even deliver multiple interrupts even before one of the former has been ended with an EOI, right? So if I were to use IPIs and timer interrupts for example, I would have the same problem again, no? Is that just something that is normally not done?

AFAICT, no, the LAPIC won't deliver most "normal" interrupts (including IRQs sent by the I/O APIC, timer IRQs and IPIs) until EOI:

![image](https://github.com/user-attachments/assets/e9f98b74-6be2-4207-9721-c9182cc154be)
(Source: Intel SDM, Volume 3, 11.8.5 Signal Interrupt Service Completition

**Comment by Freax13** [comment]
That said, maybe the LAPIC should allow accesses without a mutable reference. Given that the LAPIC accesses always use the local CPU, there's no chance of a data race, so I *think* it could be fine (unless I'm missing something else).

**Comment by tsatke** [comment]
I'm not sure about the operations deep down in the code, but unless every operation is atomic, allowing access through immutable references would be unsound, no? (Unless everything is `unsafe`).

I'm not sure whether it would be worth the hassle for me if requiring a mutable reference is formally correct (which it seems to be)

**Comment by Freax13** [comment]
> I'm not sure about the operations deep down in the code, but unless every operation is atomic, allowing access through immutable references would be unsound, no? (Unless everything is `unsafe`).

AFAIK the apic is accessed either through volatile memory accesses to special addresses outside Rust's memory model or through MSR accesses. Either way, they are atomic.

> I'm not sure whether it would be worth the hassle for me if requiring a mutable reference is formally correct (which it seems to be)

For atomic accesses, requiring only an immutable reference is also correct :)

**Comment by Freax13** [comment]
> Should I reopen this as a feature request for that change?

I'm in no way associated with this crate, I'm not a maintainer, I was just trying to help. Do whatever you feel is right.

**Comment by tsatke** [comment]
Oh haha
I don't feel like it's necessary, so I'm going to leave this closed.
